### ISSUE TITLE
Corrupt header in output

### ISSUE THREAD

**Issue by gurrhack** [chasonr/tile2360#1]
The image_size field in the header of the input file is not adjusted for the larger resolution of the output file. Setting it to 0 is the easiest fix as long as the compression field is also 0.

**Comment by chasonr** [comment]
So that's why GIMP isn't accepting my BMPs....

**Comment by chasonr** [comment]
A simple tweak fixes this. More work is needed to correctly process the larger headers that GIMP produces.
